apiVersion: batch/v1
kind: Job
metadata:
  name: checkmarx-dast-scan
spec:
  template:
    spec:
      containers:
      - name: dast-scan
        image: checkmarx/dast:latest
        env:
        - name: CX_APIKEY
          valueFrom:
            secretKeyRef:
              name: cxone-config # This should be the name of the Kubernetes secret storing your API key
              key: apikey  # The key within the secret where the API key is stored
        - name: CX_WEB_ENV
          valueFrom:
            secretKeyRef:
              name: cxone-config # This should be the name of the Kubernetes secret storing your API key
              key: web_env_id  # The key within the secret where the API key is stored         
        - name: CX_API_ENV
          valueFrom:
            secretKeyRef:
              name: cxone-config # This should be the name of the Kubernetes secret storing your API key
              key: api_env_id  # The key within the secret where the API key is stored                
        volumeMounts:
        - name: dast-home
          mountPath: "/dast_home"
        args:
        - "web"
        - "-e CX_APIKEY=$CX_APIKEY"
        - "--environment-id=$CX_WEB_ENV"
        - "--config=/dast_home/zap_config.yaml"
        - "--base-url=https://sng.ast.checkmarx.net/"
        - "--output=/dast_home/test_output"
        - "--timeout=10000"
        - "--update-interval=10"
        - "--jvm-properties=-Xmx3G"
        - "--log-level=info"
        - "--verbose"
        - "--retry=3"
        - "--retry-delay=20"
      restartPolicy: Never
      volumes:
      - name: dast-home
        hostPath:
          path: "/Users/aaron/Checkmarx/demos/dast/argocd"
          type: Directory
          volumes:

  backoffLimit: 4
