apiVersion: batch/v1
kind: Job
metadata:
  name: cx-dast-scan
spec:
  template:
    spec:
      initContainers:
      - name: download-config
        image: busybox:latest
        command: ["sh", "-c"]  # Use shell with command arguments
        args:
        - |-  # Multi-line command with proper indentation
          curl -L https://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@raw.githubusercontent.com/kcommerce/python-flask-server-bitkub/main/config/zap_config.yaml > /dast_home/zap_config.yaml
          # Added command to echo content
          cat /dast_home/zap_config.yaml
      volumes:
      - name: dast-home
        emptyDir: {}

  backoffLimit: 2
